### ISSUE TITLE
 How to completely disable the ugly "dino" game in this browser?

### ISSUE THREAD

**Issue by Dim7x0** [Alex313031/thorium-win7#11]
Or is there a version of the browser without this game built in?

Hi and thanks!

**Comment by Alex313031** [comment]
@Dim7x0 I mean all I did was add color to it. Do you think the color is ugly lol. 

No I don't make a special version with the game disabled. You shouldn't see it unless your internet is out, or you manually go to chrome://dino

**Comment by tomrow** [comment]
See if you can create a DWORD registry entry called `AllowDinosaurEasterEgg` in the folder `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\` , and set it to "1".

**Comment by Dim7x0** [comment]
> @Dim7x0 See if you can create a DWORD registry entry called `AllowDinosaurEasterEgg` in the folder `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\` , and set it to "0".

Hi it dosnt work

Work this:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Thorium\

Anyway - thanks!

**Comment by Dim7x0** [comment]
> @Dim7x0 I mean all I did was add color to it. Do you think the color is ugly lol.
> 
> No I don't make a special version with the game disabled. You shouldn't see it unless your internet is out, or you manually go to chrome://dino

The complaints are not against you, but against the idea of ​​a built-in toy) in any case, thank you very much for the support for winodws 7. I don’t know what I would have done without you.

**Comment by Alex313031** [comment]
@Dim7x0 Ahh I see. You're welcome. Try the new M119 beta! Final stable release will be coming out soon as well.
