### ISSUE TITLE
web.whatsapp.com - Is not working.

### ISSUE THREAD

**Issue by Conflituoso** [Alex313031/thorium-win7#12]
Windows 7 32bits
Thorium 109.0.5414.159

Hi.
The website https://web.whatsapp.com/  is not working.
Error code: STATUS_STACK_OVERFLOW

**Comment by gz83** [comment]
Please try again with new user data.

@Conflituoso

**Comment by Conflituoso** [comment]
Hi.
Same error.
Fresh install.
![Clipboard0111111111111111111](https://github.com/Alex313031/thorium-win7/assets/144567271/a506dd46-290e-4ff1-87ee-5a03d33c21d9)
Thorium_WIN32_109.0.5414.159.zip
Running portable/standalone.

**Comment by gz83** [comment]
Does this problem exist on chrome/chromium?

@Conflituoso

**Comment by Conflituoso** [comment]
I also use Opera and it is working perfectly.

Opera 95.0.4635.84
Chromium 109.0.5414.120

**Comment by Stepman123** [comment]
> Thorium_WIN32_109.0.5414.159.zip

Homemade repack based on thorium_win32_mini_installer.exe same error.

**Comment by JaegerFox** [comment]
109.0.5414.159 working in Windows 8.1 x64

**Comment by Alex313031** [comment]
@gz83 @JaegerFox @Conflituoso People seem to be having issues ONLY on the 32 bit version. I think it might be because I am compiling it with SSE2. Im gonna make SSE2 and SSE3 32 builds for the next release.

**Comment by Conflituoso** [comment]
Hello.
I've just tested the new version - Thorium_WIN32_109.0.5414.169.zip.zip - and everything is working perfectly well.
Thank you very much!
