### ISSUE TITLE
Disabling the Roboto font (fuzzy looking texts)

### ISSUE THREAD

**Issue by Templayer** [Alex313031/thorium-win7#13]
**Is your feature request related to a problem? Please describe.**
A lot of the Thorium self-pages use the Roboto font (instead of Segoe UI) for some reason.

Unfortunately, on my computer, the roboto font appears messy.

This is my settings page with different fonts set up, yet roboto is used (look at the Minimum font size string, how weird it looks):
![image](https://github.com/Alex313031/thorium-win7/assets/11728067/2372ba50-cae6-4c21-8a1b-366607454c94)

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/1b705038-04df-4c47-8bb1-54d0a378541e) <- this is fugly

If I use the dev tools to remove the Roboto part, now the text appears crisp clear and nice!

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/34caeb64-2954-4151-a7d5-caf15db0c1fa)

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/1a6683b5-009d-4094-8fc0-ff7544113839) <- this is what I want!

**Describe the solution you'd like, including relevant patches or source**
I don't know how to set it up so that Roboto is completely disabled. I have checked and I do not have Roboto installed on my system. Tried googling for an hour on how to disable that font browser-wide.

A setting (in flags, for example) for disabling it would be great.

**Additional Notes**
Even a workaround would be great for now... it is really screwing my eyes up.

Maybe "Disabled Fonts": [] with "Fallback Font:": "" ? If after disabling the fonts there is no font available, fallback to the fallback font?

Solutions that will not work:

* Uninstall the Roboto font. It is not installed.
* Enable ClearType in Windows - I have ClearType disabled, as it makes text in Windows blurry as hell, so that is not an applicable workaround either. I have a suspicion that Chrome depends on ClearType being turned on for some of its font rendering, thus someone not having it turned on causes some fonts to look really bad.

**Comment by Alex313031** [comment]
@Templayer Unfortunately, I don't think this is a Thorium issue. I don't change the font or font rendering logic at all compared to upstream Chromium. 
How did you get the top bar and tab strip to look like that? Could it be some third party app you are using that is causing the issue?
To verify, can you run a vanilla Chromium 109 release from here and tell me if it also has the problem > https://github.com/Hibbiki/chromium-win64/releases/tag/v109.0.5414.120-r1070088

**Comment by Templayer** [comment]
> @Templayer Unfortunately, I don't think this is a Thorium issue. I don't change the font or font rendering logic at all compared to upstream Chromium. How did you get the top bar and tab strip to look like that? Could it be some third party app you are using that is causing the issue? To verify, can you run a vanilla Chromium 109 release from here and tell me if it also has the problem > https://github.com/Hibbiki/chromium-win64/releases/tag/v109.0.5414.120-r1070088

I presume the problem is there too. As I have said, I assume the problem lies in Chrome being dependent on ClearType being turned on: (note that the text might not look as good as a picture, but before being printscreened, it actually looks good on my screen...)

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/a3b2d104-ca8c-4c6c-aa5f-9545eb2286b6)

On my Win7, ClearType looks horrible in the system and within applications, the only exception being Chromium-based browsers.

The thing is - Chrome no longer supports Win7.

> @Templayer How did you get the top bar and tab strip to look like that? Could it be some third party app you are using that is causing the issue?

All chromium-based browsers have that issue, it isn't dependent on extensions and such. I would just appreciate a single chromium browser having control over fonts, as only a few of them are causing the issue. You can consider it both as a feature request and also me asking for a workaround for disabling specific fonts.

As for the top bar - I have used vanilla chromium settings to set it up like that. Disabled the shortening of tab length (as you can see, it is actually possible to read the text in the tab even though the tab bar is full), disabled the "squishing" effect for tabs when the tab bar is full, set a dark theme (via the browser, no extension installed), and the white-to-black title bar is my Windows theme, as I do not have Win10+ where Microsoft raped the title bar styling. I.e. that white-to-black title bar gradient is used for every normal Windows... window:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/3ed717f2-b962-446f-98b7-7b67ba0040c2)

For now, I have found a half-workaround, that quite sucks - I used Adblock Plus to disable external fonts on a website. I.e. a website can reference either a local font, or a web font that is located on the same site (and not on a different domain). Via `*$font,third-party`.

This is quite a bad workaround for two reasons:

1) Legit web fonts that would look good get also blocked by this
2) Web fonts that will look bad are not blocked if they exist on the same domain as the website.

But hey, at least I can read stuff with my four dioptries and dyslexia.

**Comment by Alex313031** [comment]
@Templayer There was an excellent open source Chromium fork called Advanced Chrome for Linux and Windows. They even made a special build for Windows XP based on M54 (last version officially supporting XP was M49). It has multiple patches, one of which is directly using the native GDI font rendering of Windows. He even made a special subpage with a write-up describing a similar problem you are experiencing. 

Development was ongoing until 2022, when all of a sudden the vendor Taokaizen Software went belly up and now the site is down. The binaries are also nowhere to be found, EXCEPT:

Luckily we have this magical thing that I use ALL the time called the WayBack Machine.

Here you go sir > 
The HomePage:
https://web.archive.org/web/20221027001103/https://browser.taokaizen.com/ 
The page describing the font rendering issues and fixes (I think you should read):
https://web.archive.org/web/20221118200522/https://browser.taokaizen.com/chrome-directwrite/

And on the homepage, you can download Windows x64 and x32 builds, and Linux x64 builds, by clicking the links at the top right. For your convenience, here it the last released version for Windows x64 (based on Chromium M94):
https://web.archive.org/web/20220627191106/https://browser.taokaizen.com/download/Advanced_Chrome_Windows_v94.0.4590.0_x64.zip

**Comment by libreom** [comment]
Supermium dev @win32ss is working on getting gdi font rendering working in latest chromium

**Comment by Templayer** [comment]
> @Templayer There was an excellent open source Chromium fork called Advanced Chrome for Linux and Windows. They even made a special build for Windows XP based on M54 (last version officially supporting XP was M49). It has multiple patches, one of which is directly using the native GDI font rendering of Windows. He even made a special subpage with a write-up describing a similar problem you are experiencing.
> 
> Development was ongoing until 2022, when all of a sudden the vendor Taokaizen Software went belly up and now the site is down. The binaries are also nowhere to be found, EXCEPT:
> 
> Luckily we have this magical thing that I use ALL the time called the WayBack Machine.
> 
> Here you go sir > The HomePage: https://web.archive.org/web/20221027001103/https://browser.taokaizen.com/ The page describing the font rendering issues and fixes (I think you should read): https://web.archive.org/web/20221118200522/https://browser.taokaizen.com/chrome-directwrite/
> 
> And on the homepage, you can download Windows x64 and x32 builds, and Linux x64 builds, by clicking the links at the top right. For your convenience, here it the last released versions on my GitHub, as I archived them for safekeeping.
> 
> Windows x64: https://github.com/Alex313031/OS_and_Software_Archives/releases/download/archlabs-2023.06.07/Advanced_Chrome_Windows_v94.0.4590.0_x64.zip Windows x86: https://github.com/Alex313031/OS_and_Software_Archives/releases/download/archlabs-2023.06.07/Advanced_Chrome_Windows_v94.0.4590.0_x86.zip Linux x64: download fucked up Windows XP: https://github.com/Alex313031/OS_and_Software_Archives/releases/download/archlabs-2023.06.07/Advanced_Chrome_WinXP_v54.20.6530.0.zip

Nice. Even though I am unsure on how to proceed - the main reason why I am using Thorium is to have an up-to-date browser with backported changes so that websites won't eventually break. Using an old and no longer updated version of a modified Chrome seems to go against that. There is a newer browser that has the fonts looking correctly, and... it is Firefox. If I wanted to stay with an old version of a browser, I would probably opt to use the last Win7-compatible version of Firefox instead of Advanced Chrome.

Now if somebody can port those font changes to Chrome/Thorium, however... that would be nice.

>  Supermium dev @win32ss is working on getting gdi font rendering working in latest chromium

@Alex313031 Now if we could rebase the Win7 Thorium on S(u)permium... while cherry picking any changes you made for Thorium... that would be just perfect. Oh, yeah, I'm actually paying you via Patreon, tehehee! :D

Is that doable?

**Comment by Templayer** [comment]
I.e. doing https://github.com/Alex313031/thorium-win7/issues/3

**Comment by Alex313031** [comment]
@Templayer Yes, I am targeting M118 for rebasing Thorium on top of Supermium. It lines up nicely because, on october 10th, the final version of Chromium 109 and Electron 22 will be published, and I will make a final build based on that. Then later that week, M118 is released, and I will base it on Supermium 118.

**Comment by Templayer** [comment]
> @Templayer Yes, I am targeting M118 for rebasing Thorium on top of Supermium. It lines up nicely because, on october 10th, the final version of Chromium 109 and Electron 22 will be published, and I will make a final build based on that. Then later that week, M118 is released, and I will base it on Supermium 118.

Excellent!

**Comment by Stepman123** [comment]
![268446833-1b705038-04df-4c47-8bb1-54d0a378541e](https://github.com/Alex313031/thorium-win7/assets/8846337/f1d9f115-2a7c-4be8-806e-6cf40f3fa637)
![268446882-1a6683b5-009d-4094-8fc0-ff7544113839](https://github.com/Alex313031/thorium-win7/assets/8846337/a7598616-7b30-41a1-bc1a-7e9a70915e2c)
Since Supermium119 is now GDI capable, I checked the way the web fonts look. 
It doesn't seem to work in a similar case. There is no difference whether it is GDI or DWrite.
I guess scaling and antialiasing are different things. The problem here is scaling.

**Comment by Templayer** [comment]
SWITCHING TO GDI IN THE NEW SUPERMIUM-BASED VERSION FIXED THE ISSUE! Finally I can read shit!

Without GDI:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/a8aa8815-1941-4919-abd8-5f1d4b0db39f)

With GDI:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/365634a9-ecd6-4d8e-b44f-0959766f3f55)

...and this will forever be a story about how we beat my bad eyesight and severe dyslexia. :D
