### ISSUE TITLE
I'm asking for help!

### ISSUE THREAD

**Issue by QueenUlyana** [Alex313031/thorium-win7#14]
I was on play.google.com, everything was fine. I decided to change my account, clicked on the profile on the top right and clicked "Change Account". Authorized in the selected account and then I had some sort of profile created in my browser. All my saved tabs, history, and in general everything was deleted. I lost everything. How do I get it back? I really need help please.

**Comment by QueenUlyana** [comment]
@Alex313031 (^_^)

**Comment by Alex313031** [comment]
@QueenUlyana If you added another account, you should be able to switch. 

However, if you are using Google sync, you should sign out, then sign back in to the previous account.

Then, for adding the second one, click the profile button and at the bottom you should see an "Other profiles" section with the guest account and "+ Add". Click that to make a new profile, then once you are in that profile, sign in to your other google account.

From thereafter you can switch between the two.
