### ISSUE TITLE
Different windows 7 installers

### ISSUE THREAD

**Issue by Candlemass** [Alex313031/thorium-win7#18]
Besides the obvious 32 bit installer what's the difference between the multiple other variants?

**Comment by gz83** [comment]
The main difference is in instruction set support. You may need to check the following websites to understand the differences between different instruction sets such as SSE3, AVX, and AVX2.

https://en.wikipedia.org/wiki/SSE3

https://en.wikipedia.org/wiki/Advanced_Vector_Extensions

Different instruction sets involve differences in operations, algorithms, CPU functions, and performance. You may also need to get more information on the Internet.

**Comment by Candlemass** [comment]
> The main difference is in instruction set support. You may need to check the following websites to understand the differences between different instruction sets such as SSE3, AVX, and AVX2.
> 
> https://en.wikipedia.org/wiki/SSE3
> 
> https://en.wikipedia.org/wiki/Advanced_Vector_Extensions
> 
> Different instruction sets involve differences in operations, algorithms, CPU functions, and performance. You may also need to get more information on the Internet.

Thanks for the quick reply.

The CPU on said system supports all 3 instruction sets as per the specifications listed on the manufacturers website. Which of the 3 should I install in this case?

**Comment by gz83** [comment]
If it were me, I would probably choose the AVX2 version first, but please note: the version chosen and the performance of the corresponding version are all individual.

@Candlemass

**Comment by Candlemass** [comment]
> If it were me, I would probably choose the AVX2 version first, but please note: the version chosen and the performance of the corresponding version are all individual.
> 
> @Candlemass

@gz83

Cheers.
