### ISSUE TITLE
Installer Crashes on Windows 8.1

### ISSUE THREAD

**Issue by RUDRA78372** [Alex313031/thorium-win7#2]
Tried upgrading from 109.0.5414.120 to 109.0.5414.139 using the thorium_mini_installer, as my processor does not support AVX. But the installer does not run and crash instantly. Here is the screenshot.

![image](https://user-images.githubusercontent.com/34397749/233593861-7b2c10b7-cd66-4cdb-afd4-f15b9235e814.png)

**Comment by Alex313031** [comment]
Let me try on a machine lacking avx

**Comment by Alex313031** [comment]
@RUDRA78372 You used the regular installer (which is avx)

Try the SSE3 installer, which I just tested on a machine running win 8.1 with a core 2 duo (no AVX)

https://github.com/Alex313031/thorium-win7/releases/download/M109.0.5414.139/thorium_mini_installer_SSE3.exe

**Comment by RUDRA78372** [comment]
Thank you, this installer works. 
I am one of those people who refuse to move to Windows 10/11 until I absolutely cannot, and I am grateful to you for updating this browser for users like us. I look forward to more backported patches for thorium.

**Comment by Alex313031** [comment]
@RUDRA78372 Yup, I still use Windows 7 alongside Linux. I only use Win 10 for things I absolutely have to like some games and compiling atom-ng > https://thorium.rocks/atom-ng/

**Comment by RUDRA78372** [comment]
@Alex313031  I only use Windows 10 in a vhd to play Minecraft. For everything else, I use windows 8.1 (Have some driver issues regarding windows 7). I have used linux for a long time before, but now it is not feasible for some personal reasons. I will continue using Windows 8.1 as my primary OS as long as possible.

**Comment by RUDRA78372** [comment]
Kindly provide the SSE3 binaries for the newest release(s) if possible
