### ISSUE TITLE
pinterest.co.kr/  is not working

### ISSUE THREAD

**Issue by Conflituoso** [Alex313031/thorium-win7#20]
Windows 7 32bits
Thorium_WIN32_109.0.5414.169.zip.zip
Running portable/standalone.
Fresh install.

Hi.
The website https://www.pinterest.co.kr/  is not working.
Error code: STATUS_STACK_OVERFLOW

Working fine in Opera 95.0.4635.84 (Chromium 109.0.5414.120)

**Comment by Conflituoso** [comment]
Still having problem with the version Thorium_WIN32_SSE2_109.0.5414.172.zip

**Comment by gz83** [comment]
After version 118 is released, this problem should be solved or alleviated

**Comment by Conflituoso** [comment]
So be it, brother!  ^_^
Thanks.
