### ISSUE TITLE
Thorium_AVX_109.0.5414.172 crash on launch

### ISSUE THREAD

**Issue by Templayer** [Alex313031/thorium-win7#22]
The Thorium_AVX_109.0.5414.172.zip doesn't work for me.

Replacing my old AVX1 version (thus USER_DATA is kept) causes an empty window to appear and then a crash to desktop.

Trying to start with an empty USER_DATA also crashes (but it takes longer to crash as it is creating a profile, etc.)

Here's the crashpad report: 
[21c1feb4-788e-4786-a67d-f7fb96026ac1.dmp](https://github.com/Alex313031/thorium-win7/files/13198425/21c1feb4-788e-4786-a67d-f7fb96026ac1.dmp)

Is there anything else I can provide?

**Comment by Templayer** [comment]
System specs: 
[Templayer Win7 PC system specs.zip](https://github.com/Alex313031/thorium-win7/files/13198444/Templayer.Win7.PC.system.specs.zip)

**Comment by gz83** [comment]
I think you need to use SSE3 version

**Comment by Templayer** [comment]
> I think you need to use SSE3 version

Why? I have been using the AVX1 version for months now. Just this update borked it.

And if you were to look into the specs I have provided, my CPU supports AVX1.

If it was that issue, the application wouldn't crash, because it wouldn't even launch...

**Comment by gz83** [comment]
> > I think you need to use SSE3 version
> 
> Why? I have been using the AVX1 version for months now. Just this update borked it.
> 
> And if you were to look into the specs I have provided, my CPU supports AVX1.
> 
> If it was that issue, the application wouldn't crash, because it wouldn't even launch...

Maybe some optimization parameters are not supported by your processor, I still recommend you to test the SSE3 version

**Comment by Alex313031** [comment]
@Templayer Let me test

**Comment by Templayer** [comment]
It no longer crashes after a restart (the crashlog is a proof that it did crash originally, though).

I'm too used to Linux now - under Linux Mint, restarting won't randomly solve problems, so it didn't occur to me to try that. :D :D   

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/765255e3-98fe-4504-930d-47e993c870a3)
