### ISSUE TITLE
a little guide please

### ISSUE THREAD

**Issue by harmez7** [Alex313031/thorium-win7#23]
this is what I see whenever one of my tabs crashes on Thorium:

![Capture](https://github.com/Alex313031/thorium-win7/assets/119120324/09c98b1f-ad4c-4d34-9b42-b4ae76024f01)

I'd like to change the message to something like "Aw, Baby Jesus Fucking Christ!", because I see this a lot so I'd like a change of scenery.
can I get the instruction about how to change that?

**Comment by gz83** [comment]
This crash information is hard-coded into the code and cannot be modified manually by the user.

As for why the crash information becomes like this, please see: https://github.com/Alex313031/thorium/issues/76#issuecomment-1237866341
