### ISSUE TITLE
Create a button to "Save a webpage as a PDF" or insert this option into the "Save As" context menu.

### ISSUE THREAD

**Issue by Conflituoso** [Alex313031/thorium-win7#24]
Hi.
Sometimes I like to save some webpages as PDFs to read offline. 
I don't know if it's a widely used feature, (probably not, since it's hidden within the Print functions), but I think it would be interesting to have a button for it or, at least, there should be a suggestion of this possibility within the "Save As" context menu to "Save webpage as PDF". 

Excuse my poor English...

**Comment by gz83** [comment]
Thanks for the suggestion, but I think it's currently possible to save a web page as a PDF via the web print function, and the associated functional entry is obvious enough (to me).

**Comment by Conflituoso** [comment]
Well, at first I thought there was no such option in Thorium. I even started researching extensions that had this function. But now that I know where it is, it's really quite obvious.  ^_^  Although not very practical.

Another question, is there any way to prevent the user from closing all tabs when close the browser?

**Comment by gz83** [comment]
> Well, at first I thought there was no such option in Thorium. I even started researching extensions that had this function. But now that I know where it is, it's really quite obvious. ^_^ Although not very practical.
> 
> Another question, is there any way to prevent the user from closing all tabs when close the browser?

Just go to chrome://flags and adjust the options for Close Confirmation.

**Comment by Conflituoso** [comment]
I swear I looked, but I couldn't find this option.

How is this option named?

**Comment by gz83** [comment]
oops, sorry, the thorium-win7 version does not currently contain this experimental flag. This experimental flag may be added in the future.

@Conflituoso @Alex313031

**Comment by Conflituoso** [comment]
Okay.
Although it's not essential, it's a nice feature.
Thank you for your attention.
