### ISSUE TITLE
Which version to install?

### ISSUE THREAD

**Issue by iosoft** [Alex313031/thorium-win7#26]
Hello,

Can you pls suggest which version should I install for my old Windows 7 Laptop?

Here is the CPU-Z report - https://valid.x86.fr/lhpq1j
It has -
MMX(+), SSE, SSE2, **SSE3**, **SSSE3**, SSE4.1, SSE4.2, SSE4A, x86-64, AMD-V, **AES**, **AVX**

**Comment by gz83** [comment]
AVX Version

**Comment by iosoft** [comment]
> AVX Version

Ok.

Which one should I download? What's the difference?!
- [Thorium_AVX_109.0.5414.172.zip](https://github.com/Alex313031/thorium-win7/releases/download/M109.0.5414.172/Thorium_AVX_109.0.5414.172.zip)
- [Thorium_AVX_mini_installer.exe](https://github.com/Alex313031/thorium-win7/releases/download/M109.0.5414.172/thorium_AVX_mini_installer.exe)

**Comment by gz83** [comment]
The exe suffix is the installation version, and the zip suffix is the portable version.

> > AVX Version
> 
> Ok.
> 
> Which one should I download? What's the difference?!
> 
> * [Thorium_AVX_109.0.5414.172.zip](https://github.com/Alex313031/thorium-win7/releases/download/M109.0.5414.172/Thorium_AVX_109.0.5414.172.zip)
> * [Thorium_AVX_mini_installer.exe](https://github.com/Alex313031/thorium-win7/releases/download/M109.0.5414.172/thorium_AVX_mini_installer.exe)

**Comment by iosoft** [comment]
Thanks a lot.
Awesome project, awesome support.
