### ISSUE TITLE
google drive, discord webpage error (may be more)

### ISSUE THREAD

**Issue by xdeadstokex** [Alex313031/thorium-win7#28]
**System Details**
 - OS: both win 7 and 10
 - Thorium Version 109.0.5414.172 and below, win 32 sse2 build, win 32 sse3 build.
 - edit: further tesing, I realized that only win 32 builds have this problem.

**Problem**
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/ad930793-aa52-4eb9-803e-7fa0f2efb54d)

I reseted all settings, removed all extensions, but still aw,****! (it's also not working in incognito).
This problem only appear when i switch to thorium, chromium 107-109 dont have this problem.
welp, I guess it's time to switch to 64 bit version.

how to redo the bug:
first open google drive with any account
second, wait a few seconds and voila, aw,****!

**Comment by Stepman123** [comment]
I use the .172 sse2 build on Windows XP OCA (as my primary browser) and Windows 7. Google drive, discord are working fine.
Everything works.

**Comment by Alex313031** [comment]
@Stepman123 @xdeadstokex Finally figured out what this is, and fixed it with @gz83's help. Latest 32 Bit M122 releases should fix this.
