### ISSUE TITLE
doubt related to old hardware

### ISSUE THREAD

**Issue by mateus3c** [Alex313031/thorium-win7#29]
Is there any version of Thorium for veeeery old hardware?
I have Thorium installed on all of my machines besides the old ones, It seems they're not compatible? I'm unsure if there is any version of Thorium that supports them.

CPU: Intel Mobile Core 2 Duo T6500 2.1 GHz

**Comment by n0099** [comment]
http://valid.x86.fr/48d1t5 try using SSE4 build

**Comment by Alex313031** [comment]
@mateus3c Use the SSE3 builds. Not the avx or avx2 builds. I have made SSE4 versions for regular thorium, but for the win7 version, there is 32 bit SSE2, and 64 bit SSE3, AVX, and AVX2, depending on your CPU's capabilities.

**Comment by Alex313031** [comment]
@mateus3c @n0099 Also am providing SSE2 and SSE3 32-Bit builds.
