### ISSUE TITLE
Post M109 Updates

### ISSUE THREAD

**Issue by K4sum1** [Alex313031/thorium-win7#3]
This just got released, which is Chromium 115 but it works on Vista, 7, and 8.x
https://github.com/win32ss/supermium

Maybe you could base this off of that instead and get a more up to date Chromium version.

**Comment by Alex313031** [comment]
@K4sum1 M115 is coming soon, and I definitely want to try to make a Thorium 115 version for Win7.

**Comment by metapea** [comment]
There's now a [117 version](https://github.com/win32ss/supermium/releases/tag/v117) for supermium

**Comment by fenopa** [comment]
well this would be awesome

**Comment by Alex313031** [comment]
@metapea @fenopa @K4sum1 I am probably going to target the M118 version for migrating to using Supermium as a base to build Thorium-Win7 on.

**Comment by Stepman123** [comment]
> I am probably going to target the M118 version for migrating to using Supermium as a base to build Thorium-Win7 on.

Supermium 119 has been released. It seems that for ancient hardware (1GB RAM), an SSE2 build would be better on a base 109 or even older.
Practical usage shows that EDGE 115 and Supermium are 2-3 times slower than Thorium109. This is noticeable on heavy sites like Reddit, Discord.

**Comment by libreom** [comment]
hi @Alex313031 ,It would be helpful if you release thorium 119 based on supermium for windows 7.
Thank you

**Comment by Alex313031** [comment]
@Stepman123 @metapea @fenopa @K4sum1 Thorium M119 for Windows 7 BETA is out!

Final release should be coming any day now. I am still working out some kinks, but it is getting stabler and stabler.

**Comment by K4sum1** [comment]
> @Stepman123 @metapea @fenopa @K4sum1 Thorium M119 for Windows 7 BETA is out!
> 
> Final release should be coming any day now. I am still working out some kinks, but it is getting stabler and stabler.

I wonder, could Supermium just become part of Thorium and make this Win7 version unnecessary?

**Comment by K4sum1** [comment]
> So no, we wont be merging, but we hold each others hands lol.

I didn't mean that, I meant merging Thorium and Thorium-Win7. Probably should've just said that.

**Comment by libreom** [comment]
Please provide non avx sse4 builds

**Comment by Alex313031** [comment]
@K4sum1 Thats what I did. This repo is now a near identical mirror to the regular thorium repo. It just has a .patch file in the //patches dir to patch it for win7.

@libreom When the final M119 comes out, I will provide SSE3, SSE4, AVX, and AVX2 builds, as well as 32 bit builds. (However, the 32 bit builds are crashing, so they might have to come later)

**Comment by K4sum1** [comment]
> @K4sum1 Thats what I did. This repo is now a near identical mirror to the regular thorium repo. It just has a .patch file in the //patches dir to patch it for win7.

Yeah, what I meant was just one repo. I don't think the Windows 7 fixes have any noticeable impact on performance or anything.

**Comment by K4sum1** [comment]
How come you "will never target Vista as my minimum baseline."? If Supermium supports it, why not?

**Comment by Alex313031** [comment]
@K4sum1 It requires linking in ntdll.dll, which slows the browser down, and requires progwrp.dll, which win32ss hasn't made open source yet. Also, most people aren't using Vista. The few Vista fans/users out there can use Supermium.

However, I DID specify the minimum NT version as 6.0 instead of 6.1, because you can still run it on Vista with Extended Kernel (also made by win32ss), and I didn't want to artificially limit it that way. It just can't run on stock Windows Vista.

**Comment by libreom** [comment]
@Alex313031 do you plan to update thorium-win7 as you have updated other versions to 120 and supermium also updated to 121 https://github.com/win32ss/supermium/releases/tag/v121 No hurries. 👍

**Comment by p7r0x7** [comment]
@Alex313031 you should pin this if you want to keep this as a running dialogue about future updates for this flavor of Thorium.
