### ISSUE TITLE
low performance score using thorium compared to supermium

### ISSUE THREAD

**Issue by JaegerFox** [Alex313031/thorium-win7#31]
what the title says, using speedometer or ocane I get lower scores in thorium, I'm using the latest versions of supermium and thorium SSE4 build.

**Comment by Alex313031** [comment]
@JaegerFox Its cuz of the version differences. They made some good speed enhancements upstream between 109 and 119.

Thorium for windows 7 based on 119 will be coming out shortly, probably within the next week.
