### ISSUE TITLE
ican't find 32bit version of the latest thorium for win7!

### ISSUE THREAD

**Issue by krimnassim** [Alex313031/thorium-win7#35]
hi.thanks for creating this awesome project and make browsing possible for w7 my issue that i can't find 32bit version of the latest  thorium browser can u kindly provide us with 32bit version for w7 and thanks

**Comment by Alex313031** [comment]
@krimnassim This is a beta, and only an AVX installer is provided. However, I am building the final releases as we speak. Check back tomorrow and they will be there.

**Comment by krimnassim** [comment]
thanks
