### ISSUE TITLE
STATUS_ACCESS_VIOLATION error when loading Google Drive web page

### ISSUE THREAD

**Issue by Dlix6** [Alex313031/thorium-win7#4]
**System Details**
 - OS: Windows 8.1 Pro 32-bit
 - Thorium Version 109.0.5414.141 (Official Build) (32-bit)

**Problem**
After navigating to 
https://drive.google.com/drive/my-drive 
as soon as Google Drive web page loads Thorium tab goes blank and displays error message: 
Something went wrong while displaying this webpage
Error code: STATUS_ACCESS_VIOLATION

**Screenshots**
![Capture](https://github.com/Alex313031/thorium-win7/assets/134600876/1362452d-3d52-4172-8362-5eb631fe1039)

**Additional Notes**
I run 32-bit SSE2 build in portable mode on 32-bit Windows 8.1 Pro

**Comment by RUDRA78372** [comment]
Just checked on the 64-bit version of Thorium (Win 8.1 Embedded Industry Pro), the webpage works here. Probably an error for the 32-bit version only.

**Comment by Alex313031** [comment]
@Dlix6 I can test in a win8 VM.

**Comment by Alex313031** [comment]
@Dlix6 @RUDRA78372 I can reproduce this. It doesnt happen on Windows 7 32 bit. Only 8.1 (and I am assuming 8.0 but Im not gonna test that)

**Comment by Dlix6** [comment]
The issue persists in new version (thorium_WIN32_109.0.5414.152.zip). 
I've had that version of Chromium v109.0.5414.120 32bit installed before on same computer with Windows 32bit Pro and Google Drive webpage worked just fine.

**Comment by gz83** [comment]
It is possible that the 32-bit version cannot apply for more memory, which leads to this problem. This problem needs further investigation

@RUDRA78372 @Alex313031 @Dlix6

**Comment by Alex313031** [comment]
@Dlix6 Next release I am going to make SSE3 and SSE2 32 bit versions. You can try that next.

**Comment by Dratas** [comment]
Hello have same issue,but with discord.com after login with user/pass.OS WIN7-Ultimate 32-bit,using this portable version M109.0.5414.159 32-bit,its latest so far i see.

**Comment by Kame03** [comment]
Hello, I have the same issue but with Discord. 
![image](https://github.com/Alex313031/thorium-win7/assets/98698826/331b5283-db17-4419-a73e-87f66da5a513)

**Comment by Alex313031** [comment]
@Dratas @RUDRA78372 @Kame03  @Dlix6 This should all be fixed in the latest M122 release.
