### ISSUE TITLE
No AES-NI but AVX acceleration

### ISSUE THREAD

**Issue by libreom** [Alex313031/thorium-win7#40]
This is my cpu features
![image](https://github.com/Alex313031/thorium-win7/assets/111110599/8fa3281e-f4af-4012-8118-7b280e3ffd48)
I am currently using SSE4 build which works, I tried avx build but it crashes after a flash of window, if it can be made to run, please tell, maybe with flag -maes you recently added

**Comment by Alex313031** [comment]
@libreom Only the I3 and Celeron of sandy bridge and ivy bridge have avx but not aes. Every other AVX capable CPU whether AMD or Intel has AES.

Because this is a very specific CPU issue, I wont be making AVX -AES builds. You can use the SSE4 builds though.

**Comment by libreom** [comment]
Ok👍, you can close this issue
