### ISSUE TITLE
Add new subfolder 'Bookmarks'

### ISSUE THREAD

**Issue by skarsgal** [Alex313031/thorium-win7#41]
Hi Alex,
Please add a new subfolder '**Bookmarks**' in '\USER_DATA\Default' and store in this new subfolder these two files:
**Bookmarks** and **Bookmarks.bak**.
because so I can store in this new subfolder also my files 'bookmarks_24_01_xx.html' and then import them inside program 'URL Gather'
https://web.archive.org/web/20190717131208/http://www.zqware.com/
http://www.zqware.com/urlgather/index.html
Thanks

**Comment by Alex313031** [comment]
@skarsgal You can do this yourself, Im not going to modify the code which would break some users workflows.
