### ISSUE TITLE
[FR] Flags from ungoogled chromium

### ISSUE THREAD

**Issue by Request-timed-out** [Alex313031/thorium-win7#42]
Hi Alex, the new version of Thorium is amazing! On my win8.1 its performance is 125% of average chromium, I love it a lot! And it has never crashed so far. Can you add more flags (like `#close-window-with-last-tab`, `#remove-grab-handle` and so on...) from ungoogled chromium to make Thorium more secure and more customizable? I also checked the flags in Supermium, there's an ungoogled flag WIP, hope u can finish it together and add to respective updates, thx & keep up good work!!

**Comment by gz83** [comment]
Only patches that are useful to us and do not break usability will be added, other types of patches may not be added

**Comment by ruboard** [comment]
I would also add #close-window-with-last-tab

**Comment by Alex313031** [comment]
@Request-timed-out @ruboard Added! > https://github.com/Alex313031/thorium-win7/commit/a8480f48ed620f50e294d1c9ba4e2c307f49b578

**Comment by Alex313031** [comment]
@Request-timed-out These flags are now in the M122 release.
