### ISSUE TITLE
Weird behaviors

### ISSUE THREAD

**Issue by jiusiwu** [Alex313031/thorium-win7#43]
"..this tab's process has gone bye bye"

ublock origin extension keeps crashing

![IMG_20240117_183218](https://github.com/Alex313031/thorium-win7/assets/153227312/57b9b495-744a-4430-92c5-d780a5634cae)
![ublock crash](https://github.com/Alex313031/thorium-win7/assets/153227312/18b1254a-6925-4f52-8052-cdd66e65b15c)

**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**

**Screenshots**

**Additional Notes**

**Comment by jiusiwu** [comment]
Version 119.0.6045.214 (Official Build) (32-bit), WIN32 SSE2

**Comment by Alex313031** [comment]
@jiusiwu dang. The 32 bit thorium releases have always seemed to have issues.

**Comment by Alex313031** [comment]
@jiusiwu Finally found out the issue, and fixed it. Latest M122 32 bit Win7 releases should work fine.
