### ISSUE TITLE
Add bookmark button at the top left.

### ISSUE THREAD

**Issue by ant1994ant** [Alex313031/thorium-win7#44]
Hello, thanks for your work!
If possible, please add a bookmark button at the top left, like it is in Firefox, Maxthon, Cent... 
https://www.upload.ee/image/16113798/2024-1-1_10-56-31.png 
It would also be nice to have an x64 version of the browser.
Thank you.

**Comment by Alex313031** [comment]
@ant1994ant There is an x64 version of the browser. Look at the release notes for the 32 bit version, right underneath it is the x64 bit versions.

Also, I don't know how to add that. I can add the button, but I don;t know how to make it actually show a bookmark list. Cent browser is not open source so I can't look at that.

**Comment by gz83** [comment]
I think the existing bookmark function is sufficient. This function of cent browser is duplicated with the existing bookmark function.

**Comment by ant1994ant** [comment]
> I think the existing bookmark function is sufficient. This function of cent browser is duplicated with the existing bookmark function.

You can think whatever you want ;)

**Comment by ant1994ant** [comment]
> Also, I don't know how to add that. I can add the button, but I don't know how to make it actually show a bookmark list. Cent browser is not open source so I can't look at that.

Besides Cent, this button is available in many browsers, for example Firefox...

**Comment by Alex313031** [comment]
@ant1994ant Probably wont add this. Doing anything to the top bar UI other than modifying the icons or names of things is a pain in the butt. Plus, Thorium's UI isn't supposed to deviate too much from Chromium's
