### ISSUE TITLE
"Description/Info Ballons" quickly disappear after appearing when Mouse Pointing

### ISSUE THREAD

**Issue by cnt76** [Alex313031/thorium-win7#45]
**System Details**
 - OS:  Windows 7 Professional 32-bit
 Thorium Version 119.0.6045.214 SS3

**Problem**
When you mouse point over a link to view the description ballon (or full name of the video in Youtube, Mails & other links), the tooltip (Info Ballons) appears for a very brief moment and disappears too fast.

**Comment by Alex313031** [comment]
@cnt76 Is this with the hover card flag disabled in chrome://flags?

**Comment by n0099** [comment]
https://github.com/win32ss/supermium/issues/155

**Comment by cnt76** [comment]
> @cnt76 Is this with the hover card flag disabled in chrome://flags?

no, i didnt touch anything, is all in default

**Comment by cnt76** [comment]
> [win32ss/supermium#155](https://github.com/win32ss/supermium/issues/155)

Yes exacly, but Tooltips quickly disappear, for the last 3 versions in supermium & thorioum, so I thought, leave the issue here too.
Practically, this problem is very annoying, so I decided to continue using another browser until they can fix it.
​

**Comment by cnt76** [comment]
> @cnt76 Is this with the hover card flag disabled in chrome://flags?

Is this with the hover card flag disabled in chrome://flags?

no, i didnt touch anything, is all in default
I used the last 3 versions of supermium & thorium ss3 32bits & the problem is still there
