### ISSUE TITLE
I CAN'T DISABLE AUTOPLAY IN THORIUM!!

### ISSUE THREAD

**Issue by krimnassim** [Alex313031/thorium-win7#46]
Hi @Alex313031,i can't find Autoplay in thorium setting and i can't block videos from auto playing in websites,i like to block autoplay on specific websites like twitter X and other sites and allow autoplay on some sites i can't find the option in the setting to do it,i only found a flag but it won't work in on most sites only worked on youtube but when i click on yt video it goes back to autoplay and i can't block specific sites,can u bring back autoplay in thorium setting?i really appreciate ur work Alex,THANKS.
![Capture](https://github.com/Alex313031/thorium-win7/assets/62130284/2b01f35f-c845-4bbc-bbb2-8b31955a6d47)

**Comment by Alex313031** [comment]
@krimnassim You should set it to "user gesture required"

**Comment by krimnassim** [comment]
@Alex313031 i did try "user gesture required"but won't block autoplay on sites like twitter tiktok instagram,is it possible to add autoplay in thorium setting like shown in the screenshots and thanks for ur reply and ur time.
![Capture](https://github.com/Alex313031/thorium-win7/assets/62130284/db2f6ea5-8b43-4a6d-abc8-d63c4257aee5)
![vv](https://github.com/Alex313031/thorium-win7/assets/62130284/135dfe00-03c1-4519-9009-eedda1e1f910)

**Comment by jiusiwu** [comment]
Try installing this extension:

Disable HTML5 Autoplay (Reloaded)
https://chromewebstore.google.com/detail/disable-html5-autoplay-re/cafckninonjkogajnihihlnnimmkndgf

**Comment by krimnassim** [comment]
i tried that extension it worked but it's not perfect there is a loading circle on the twitter when scrolling and when i randomly click on the page the video start playing,it should work only when i click on the play button,i think autoplay should be built-in in the browser u don't have to install extension i hope Alex find a way to add it in thorium settings on future releases thanks for ur help@jiusiwu.
