### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by Sam0l1y** [Alex313031/thorium-win7#5]
There is a mixture of English and another language selected by the user (mostly where "chromium" is mined to "thorium"

**Comment by Alex313031** [comment]
@Sam0l1y This would require a huge effort that I am not willing to put in right now. I would have to update the strings for every language, and then regenerate the hashes for them, and rebuild for each architecture. I am aware that certain UI elements still use "Chromium" when in a non-english language.

@gz83 Does this happen to you when you run thorium on your win 11 laptop with the language set to chinese?

**Comment by gz83** [comment]
> Does this happen to you when you run thorium on your win 11 laptop with the language set to chinese?

I haven't found this problem for now while using Thorium, but I need to make some more observations and if I find this problem, I will report it here.

@Alex313031

**Comment by Sam0l1y** [comment]
My friends and I have Russian. Installed Windows Thin PC, on the second Elementary OS, on the third Windows 11, on the fourth ThoriumOS and so on. Friends have different Unix, Windows. In addition, I agreed with the school administration that they install Thorium on all old computers with the old 32-bit Win7 (they do not want to change the system to ThoriumOS :( )

**Comment by Sam0l1y** [comment]
And yes, the same is in ThoriumOS in the settings and not only
