### ISSUE TITLE
(Windows 8.1) AVX release doesn't work on a CPU that supports AVX

### ISSUE THREAD

**Issue by dnchshrp** [Alex313031/thorium-win7#54]
**System Details**
 - OS: Windows 8.1 x64
 - Thorium [M119.0.6045.214](https://github.com/Alex313031/thorium-win7/releases/tag/M119.0.6045.214)
 - CPU: ![aida64_WCPn7jIEJw](https://github.com/Alex313031/thorium-win7/assets/113385003/76a5aef8-b30c-4142-a0ed-0b2c10f0ae90)

**Problem**
 The AVX build doesn't work: it shows a white window and closes immediately(My CPU supports AXV instructions as showed in the screenshot above)

**Screenshots**
https://github.com/Alex313031/thorium-win7/assets/113385003/09222d1b-024d-4125-9fc7-965bd6d60821

**Additional Notes**
The SSE4 builds work but AVX don't

**Comment by gz83** [comment]
It may be caused by your processor lacking some other instruction sets (except AVX). When we compile the AVX version, we not only pass the AVX instruction set parameters, but also pass other instruction set parameters.

@dnchshrp

**Comment by dnchshrp** [comment]
All instruction sets that are supported on my CPU are shown on a screenshot above

**Comment by dnchshrp** [comment]
Is it possible to compile a version that would use AVX instructions for higher perforance but wouldn't require AES instructions?

**Comment by gz83** [comment]
Sorry, we don't have much resources and time to compile more versions. Compiling Chromium once takes several hours (for me, it takes nearly four hours) and the computer is under high load during the compilation process.

In addition, using a more advanced instruction set does not necessarily mean that the performance is good. Browser performance varies from person to person, so just choose the one that suits you.

@dnchshrp
