### ISSUE TITLE
AVX based build crashes on intel Core i3-2328M (Sandy Bridge)

### ISSUE THREAD

**Issue by mjishnu** [Alex313031/thorium-win7#55]
**System Details**
 - OS: Windows 7
 - Thorium Version: m119 final

**Problem**
The app crashes on my [intel Core i3-2328M](https://www.intel.com/content/www/us/en/products/sku/70927/intel-core-i32328m-processor-3m-cache-2-20-ghz/specifications.html) when using  avx based build, app works fine on sse4, no crashes.

**Comment by n0099** [comment]
#54

**Comment by mjishnu** [comment]
damn mine doesn't support AES. so I guess would need to stick with SSE4 :(
