### ISSUE TITLE
Extensions icon unaffected by 'Disable Thorium Top Bar Icons' flag

### ISSUE THREAD

**Issue by Quisquose** [Alex313031/thorium-win7#58]
**System Details**
 - OS: [Windows 7]
 - Thorium Version [122.0.6261.132]

**Problem**
The description of the '**Disable 'Thorium Top Bar Icons**' flag says: "_Disables the custom colored top bar icons in Thorium, and restores the default grey Chromium icon colors_".

When this flag is enabled, it successfully makes the all top bar icons grey _except_ for the Extensions icon (which remains blue). 

Seeing as the stated purpose of this flag is to restore the default grey icons, it should include the Extensions icon too. It's distracting and looks ugly having this one single icon standing out as the only coloured icon (instead of matching the rest of the theme).

**Screenshots**
![Thorium flag](https://github.com/Alex313031/thorium-win7/assets/7541455/a21df3d6-31ba-4a99-93e4-b58f8f11895d)

**Comment by gz83** [comment]
Currently this flag will not affect the extension icons you pointed out, and we still intend to retain some of the modified icons.

In addition, we will redraw some icons in the future.

**Comment by Quisquose** [comment]
> "we still intend to _retain_ some of the modified icons"

To clarify, I was not asking for the icon to be removed or redrawn, simply for it to be made grey when the flag is enabled. The Extensions icon is grey in Supermium, so presumably this is the normal state of the icon and specific action was taken by Alex to make it blue.

For people who want the coloured icons, they would not enable this flag (which is the Thorium default setting) and the coloured icons would remain.

However, those enabling the flag obviously want grey icons (as per the flag's description) but this is currently inconsistent because it is only partially implemented.

**Comment by gz83** [comment]
> > "we still intend to _retain_ some of the modified icons"
> 
> To clarify, I was not asking for the icon to be removed or redrawn, simply for it to be made grey when the flag is enabled. The Extensions icon is grey in Supermium, so presumably this is the normal state of the icon and specific action was taken by Alex to make it blue.
> 
> For people who want the coloured icons, they would not enable this flag (which is the Thorium default setting) and the coloured icons would remain.
> 
> However, those enabling the flag obviously want grey icons (as per the flag's description) but this is currently inconsistent because it is only partially implemented.

What I said earlier about redrawing the icon is that we are working on our side, not that you are asking us to redraw the icon.

At the same time, it is intentional that some icons currently remain in Thorium style.

**Comment by Alex313031** [comment]
@gz83 @Alex313031 Yeah, but with CR23 (the 2023 UI refresh google is pushing), I will add this icon to the list of ones reverted back to grey with this flag.
