### ISSUE TITLE
Considerable launch delay in 122 / SSE3 / W7x86

### ISSUE THREAD

**Issue by naryfa** [Alex313031/thorium-win7#59]
**System Details**
 - OS: [Windows 7x86]
 - Thorium Version [M122.0.6261.132 - thorium_WIN32_SSE3_mini_installer.exe]

**Problem**
Launching the app adds considerable amount of wait time. Had to revert back to version 119.

**Additional Notes**
The app launches blank for several seconds. Perhaps my old Core 2 Duo T7600 struggles with this version?
Has anything changed in regards to rendering?

**Comment by Alex313031** [comment]
@naryfa No changes in rendering. I can try the 32 bit SSE3 version on my Core 2 Duo laptop. Im using the 64 bit SSE3 version and I don't notice any difference from previous releases.

However, I don't really test the 32 bit builds, and they are provided as a convenience.

**Comment by naryfa** [comment]
I understand. Thank you for testing on your end. 64bit OS on my old laptop would be a waste as the chipset allows only for 3.2GB usable. Every precious ounce of RAM is gold here so I'm forced to run x86.
